# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa3a757645a50934fe26752d88f46726c0a5ee833b0ade6ed3471231e9053c31b086e8ad42bd63b1df3e936380cf819670c3b51439c82bce154d512996201895

test:
  secret_key_base: d66b90104e1528e47ed2ea10f39f1e168f5f6ac6c7e1df3a07d672cfbe54b5eeb803770471b939e0589995af9fb1ce5090d0779872c612aabccd39cb1bdf4c1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
